### PR TITLE
added configurable runtime.bundle.service.name

### LINKED ISSUE #2548: Make runtime bundle serviceName configurable in the acceptance tests
The notification services tests hardcode in the test payload rb-my-app as a serviceName for the runtime bundle making it hard to reuse the tests in a different environment where the runtime bundle URL is different, so that should be made configurable as well

### PR DESCRIPTION
**Pull request by mteodori**
fixes Activiti/Activiti#2548

### CODE REVIEW

**Comment by igdianov** [comment]
@mteodori 👍

**Comment by ryandawsonuk** [comment]
Looks good but currently having trouble with pipelines so can't merge right now. http://jenkins.jx.35.240.9.95.nip.io/job/Activiti/job/activiti-build/job/7.0.x/12/console resulted in https://github.com/Activiti/Activiti/pull/2556/files , which is a mixture of the 7.0.x and 7.1.x release trains - more specifically the 7.0.x train made a commit to overwrite a PR on the 7.1.x train. We're working to fix updatebot and get pipelines working again and have submitted a PR for it - https://github.com/jenkins-x/updatebot/pull/73

**Comment by igdianov** [comment]
@mteodori It looks good to me. I will not use Github approval, since it will trigger Mergify to merge this PR until @ryandawsonuk confirms the pipelines are working.

**Comment by mteodori** [comment]
@igdianov no problem this can wait, we're cool with the patch on top of 7.0.0.GA at https://github.com/Activiti/activiti-cloud-acceptance-scenarios/tree/7.0.0.GA-patched-for-notification-service-tests

**Comment by ryandawsonuk** [comment]
Now merging this as we have a resolution for https://github.com/Activiti/Activiti/issues/2577

**Pull request merged**
