### PR TITLE
fix(versions): update Activiti/activiti-cloud-acceptance-tests versions into develop

### PR DESCRIPTION
**Pull request by ghost**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.cloud.build:activiti-cloud-parent` to: `7.1.19`

### CODE REVIEW

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.build:activiti-cloud-parent 7.1.19 org.activiti.cloud.build:activiti-cloud-dependencies-parent 7.1.19

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.96

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.97

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.98

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.99

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.build:activiti-cloud-parent 7.1.20 org.activiti.cloud.build:activiti-cloud-dependencies-parent 7.1.20

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.100

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.build:activiti-cloud-parent 7.1.21 org.activiti.cloud.build:activiti-cloud-dependencies-parent 7.1.21

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.101

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.102

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.103

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.build:activiti-cloud-parent 7.1.22 org.activiti.cloud.build:activiti-cloud-dependencies-parent 7.1.22

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.build:activiti-cloud-parent 7.1.23 org.activiti.cloud.build:activiti-cloud-dependencies-parent 7.1.23

**Comment by ghost** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind maven org.activiti.cloud.api:activiti-cloud-api-dependencies 7.1.104

**Comment by erdemedeiros** [comment]
@Mergifyio refresh

**Pull request merged**
